import random

CONSTRAINTS = {
    "Test": [
        "Only select bowlers with bowling average above 30 OR batsmen with batting average below 35 — build the best squad of underdogs",
        "Only select players who have scored a century or taken a 5-wicket haul in Australia",
        "Only select players who have scored a century or taken a 5-wicket haul in England",
        "Every player must have at least 1 Test wicket AND at least 200 Test runs",
        "Only select pace bowlers from the subcontinent OR spin bowlers from SENA countries",
        "Only select players NOT from India, Australia, or England",
        "Only select left-handed batsmen OR left-arm bowlers",
        "Only select players from the subcontinent (India, Pakistan, Sri Lanka, Bangladesh)",
        "Only select players from SENA countries (South Africa, England, New Zealand, Australia)",
        "Only select players who debuted in Test cricket between 2000 and 2015",
        "Only select players who have scored at least one Test duck AND at least one Test century — the feast-or-famine XI",
        "Only select all-rounders and wicket-keepers — no specialist batsmen or bowlers",
        "Only select players who have taken at least one Test wicket AND scored at least one Test fifty",
        "Only select players with a Test batting average above 40 OR bowling average below 30",
        "Only select players who have played 50+ Test matches",
        "Only select players who have scored at least 10 Test centuries",
        "Only select players from Southern Hemisphere nations",
        "Only select spin bowlers OR batsmen from the West Indies, Sri Lanka, or Pakistan",
        "Only select players who have scored a century or taken a 5-wicket haul in India",
        "Only select right-arm fast bowlers OR right-handed batsmen who bowl part-time",
        "Only select opening batsmen OR new-ball bowlers",
        "Only select players with 3000+ Test runs AND at least 1 Test century",
        "Only select players who have played Tests against at least 5 different countries",
        "Only select players who have never scored a Test century but have played 20+ Tests — the unsung warriors",
        "Only select players who have both batted and bowled in Test cricket — minimum 500 runs AND 10 wickets",
        "Only select players who have scored a century against India OR taken a 5-wicket haul against Australia",
        "Only select players whose Test career spans at least 10 years",
        "Only select players who have batted at number 6 or lower AND have a Test fifty",
        "Only select players who have scored a Test century AND taken at least 1 Test catch — no pure bowlers who can't field",
        "Only select players from countries that have never won a Test series in Australia",
        "Only select right-handed batsmen and right-arm bowlers only — no lefties allowed",
        "Only select players who debuted before the year 2000",
        "Only select players who have scored a Test century OR taken 5+ wickets in a single innings in Asia",
        "Only select fast bowlers OR batsmen who bat in the top 3",
        "Only select players from the Caribbean, Africa, or Oceania",
        "Only select pace bowlers with 150+ Test wickets OR batsmen with 8000+ Test runs",
        "Only select players who have scored a Test century in a losing cause OR taken a 5-wicket haul in a losing cause",
        "Only select bowlers with 100+ Test wickets OR batsmen with 5000+ Test runs",
        "Only select players who have played at least one Test at Lord's",
        "Only select players who have scored a fifty in both innings of a Test match",
        "Only select players who have taken at least 5 wickets in a Test innings",
        "Only select players who debuted in Tests after turning 24 — the late bloomers",
        "Only select left-handed batsmen from outside Asia OR right-arm spinners from Asia",
        "Only select players who have won a Man of the Match award in Tests",
        "Only select players who have scored a Test century on debut OR taken a 4-wicket haul on debut",
        "Only select players who have captained their country in Test cricket",
        "Only select players who have captained their country in Tests OR have never scored a Test duck — the reliable XI",
        "Only select players with 30+ Test catches OR 10+ Test stumpings — safe hands only",
        "Only select players who have hit at least 10 sixes in Test cricket",
        "Only select players who have scored at least 5 Test ducks — the risk-takers XI",
    ],
    "ODI": [
        "Only select bowlers with bowling average above 30 OR batsmen with batting average below 30 — the best of the rest",
        "Only select players who have scored a century or taken a 4-wicket haul in a World Cup match",
        "Only select left-handed batsmen OR left-arm bowlers",
        "Only select players NOT from India, Australia, or England",
        "Only select players from Asian countries only",
        "Only select players from countries that have won the Cricket World Cup",
        "Only select players who have played 100+ ODIs",
        "Only select right-handed batsmen and right-arm bowlers only — no lefties allowed",
        "Only select players who debuted in ODI cricket after 2005",
        "Only select wicket-keepers OR spin bowlers",
        "Only select fast bowlers OR top-order batsmen (top 4)",
        "Only select players from outside Asia",
        "Only select players from the Caribbean, Africa, or Oceania",
        "Every player must have at least 1 ODI wicket AND at least 100 ODI runs",
        "Only select pace bowlers from the subcontinent OR spin bowlers from SENA countries",
        "Only select players who have scored an ODI century in a losing cause — the heroic losers",
        "Only select players who have scored at least 5 ODI centuries",
        "Only select players with an ODI batting average above 35 OR bowling average below 28",
        "Only select players who have played in a Cricket World Cup semi-final or final",
        "Only select all-rounders who have both 1000+ ODI runs AND 50+ ODI wickets",
        "Only select players who have scored a century AND taken a wicket in the same ODI match",
        "Only select players who debuted between 1995 and 2010",
        "Only select players who have never scored an ODI century but have played 50+ ODIs — the unsung workhorses",
        "Only select players who have scored a fifty or taken 3+ wickets in a World Cup knockout match",
        "Only select players who have played ODIs on at least 3 different continents",
        "Only select players who have captained their country in ODIs",
        "Only select players who have captained their country in a World Cup OR scored a World Cup century",
        "Only select players with 20+ ODI catches OR 10+ ODI stumpings",
        "Only select players who have hit at least 50 sixes in ODI cricket",
        "Only select players who have scored at least 10 ODI ducks — the boom-or-bust XI",
    ],
    "T20I": [
        "Only select players who have played 30+ T20I matches",
        "Only select players who have scored 1000+ T20I runs OR taken 50+ T20I wickets",
        "Only select left-handed batsmen OR left-arm bowlers",
        "Only select players NOT from India, Australia, or England",
        "Only select players who have played in a T20 World Cup",
        "Only select players from Asian countries only",
        "Only select spin bowlers OR wicket-keeper batsmen",
        "Only select right-arm pace bowlers OR left-handed batsmen",
        "Only select players from countries that have won the T20 World Cup",
        "Only select players who debuted in T20Is after 2015",
        "Only select all-rounders who have both 500+ T20I runs AND 20+ T20I wickets",
        "Only select players from outside the subcontinent",
        "Only select players who have hit 20+ sixes in T20I cricket",
        "Only select fast bowlers OR explosive top-order batsmen (top 3)",
        "Only select players from the Southern Hemisphere",
        "Only select players who have represented their country in all three formats",
        "Only select players who have scored at least one T20I fifty but never a T20I century — the consistent but not explosive",
        "Every player must have at least 1 T20I wicket AND at least 50 T20I runs",
        "Only select pace bowlers from Asia OR spin bowlers from outside Asia",
        "Only select players who have scored a fifty or taken 3+ wickets in a T20 World Cup match",
        "Only select players who debuted in T20Is between 2007 and 2018",
        "Only select players who can bat AND bowl — minimum 200 T20I runs AND 5 T20I wickets",
        "Only select players who have never hit a T20I century but have played 25+ T20I matches",
        "Only select players who have scored a T20I fifty OR taken a T20I 4-wicket haul",
        "Only select players who have taken at least one 3-wicket haul in T20Is AND scored at least one T20I thirty",
        "Only select players who have captained their country in T20Is",
        "Only select players who have captained their country in a T20 World Cup OR scored a T20 World Cup fifty",
        "Only select players with 10+ T20I catches — the sharp fielders",
        "Only select players who have hit at least 10 sixes in T20I cricket",
        "Only select players who have taken at least 2 catches in a single T20I match",
    ],
}


def get_random_constraint(game_format):
    pool = CONSTRAINTS.get(game_format, CONSTRAINTS["ODI"])
    return random.choice(pool)
